# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lstream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlstream.proto\"G\n\rLockOpRequest\x12\x0f\n\x07lock_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\x05\"\x96\x01\n\x0bLockOpReply\x12\x0f\n\x07lock_id\x18\x01 \x01(\t\x12\x11\n\tis_leader\x18\x02 \x01(\x08\x12\x13\n\x0bis_timedout\x18\x03 \x01(\x08\x12\x15\n\ris_successful\x18\x04 \x01(\x08\x12\x11\n\tclient_id\x18\x05 \x01(\t\x12\x12\n\nrequest_id\x18\x06 \x01(\x05\x12\x10\n\x08is_valid\x18\x07 \x01(\x08\x32\x62\n\nLockStream\x12)\n\x07\x61\x63quire\x12\x0e.LockOpRequest\x1a\x0c.LockOpReply\"\x00\x12)\n\x07release\x12\x0e.LockOpRequest\x1a\x0c.LockOpReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lstream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCKOPREQUEST._serialized_start=17
  _LOCKOPREQUEST._serialized_end=88
  _LOCKOPREPLY._serialized_start=91
  _LOCKOPREPLY._serialized_end=241
  _LOCKSTREAM._serialized_start=243
  _LOCKSTREAM._serialized_end=341
# @@protoc_insertion_point(module_scope)
