# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x1a\x1cgoogle/protobuf/struct.proto\"d\n\x11\x41skForVoteRequest\x12\x0e\n\x06\x63_term\x18\x01 \x01(\x05\x12\x0c\n\x04\x63_id\x18\x02 \x01(\x05\x12\x18\n\x10\x63_last_log_index\x18\x03 \x01(\x05\x12\x17\n\x0f\x63_last_log_term\x18\x04 \x01(\x05\"2\n\x0f\x41skForVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tvoted_yes\x18\x02 \x01(\x08\"B\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12(\n\x07\x63ommand\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x98\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x05\x12\x15\n\rprev_log_term\x18\x04 \x01(\x05\x12\x14\n\x0c\x63ommit_index\x18\x05 \x01(\x05\x12\x1a\n\x07\x65ntries\x18\x06 \x03(\x0b\x32\t.LogEntry\"h\n\x12\x41ppendEntriesReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x18\n\x10\x63onflicting_term\x18\x02 \x01(\x05\x12\x19\n\x11\x63onflicting_index\x18\x03 \x01(\x05\x12\x0c\n\x04term\x18\x04 \x01(\x05\x32\x9c\x01\n\x14RaftConsensusService\x12=\n\x13handle_request_vote\x12\x12.AskForVoteRequest\x1a\x10.AskForVoteReply\"\x00\x12\x45\n\x15handle_append_entries\x12\x15.AppendEntriesRequest\x1a\x13.AppendEntriesReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASKFORVOTEREQUEST._serialized_start=44
  _ASKFORVOTEREQUEST._serialized_end=144
  _ASKFORVOTEREPLY._serialized_start=146
  _ASKFORVOTEREPLY._serialized_end=196
  _LOGENTRY._serialized_start=198
  _LOGENTRY._serialized_end=264
  _APPENDENTRIESREQUEST._serialized_start=267
  _APPENDENTRIESREQUEST._serialized_end=419
  _APPENDENTRIESREPLY._serialized_start=421
  _APPENDENTRIESREPLY._serialized_end=525
  _RAFTCONSENSUSSERVICE._serialized_start=528
  _RAFTCONSENSUSSERVICE._serialized_end=684
# @@protoc_insertion_point(module_scope)
