RAFT_NODE_STATE = (FOLLOWER, CANDIDATE, LEADER) = ("FOLLOWER", "CANDIDATE", "LEADER")

ELECTION_TIMEOUT = 400

ELECTION_TIMEOUT_RANGE = (ELECTION_TIMEOUT_RANGE_START, ELECTION_TIMEOUT_RANGE_END) = (
    ELECTION_TIMEOUT,
    ELECTION_TIMEOUT * 2,
)

HEARTBEAT_PERIOD = ELECTION_TIMEOUT / 2
RPC_FAILURE_BACKOFF = ELECTION_TIMEOUT / 2
